apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: python-app-0326 
  janus-idp.io/tekton: python-app-0326
  backstage.io/kubernetes-id: python-app-0326
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: python-app-0326
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  